- name: Print parameters from parameter store
  hosts: localhost
  connection: local
  tasks:
    - name: Print parameter from parameter store
      debug: msg="{{ lookup('aws_ssm', 'sriram', region='us-east-1' ) }}"